---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: payment-mvp
  name: payment-mvp-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: payment-mvp-app
  template:
    metadata:
      labels:
        app: payment-mvp-app
    spec:
      containers:
        - name: app
          image: payment_mvp:latest
          readinessProbe:
            httpGet:
              path: /api/health
              port: api-port
            initialDelaySeconds: 5
            periodSeconds: 10
          env:
            - name: PAYMENT_MVP_HOST
              value: "0.0.0.0"
            - name: PAYMENT_MVP_WORKERS_COUNT
              value: "10"
          resources:
            limits:
              memory: "200Mi"
              cpu: "100m"
          ports:
            - containerPort: 8000
              name: api-port
---
apiVersion: v1
kind: Service
metadata:
  namespace: payment-mvp
  name: payment-mvp-app-service
spec:
  selector:
    app: payment-mvp-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: api-port
      name: api-port

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: payment-mvp-app
  namespace: payment-mvp
  labels:
    name: payment-mvp-app
spec:
  rules:
    - host: payment-mvp.local
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: payment-mvp-app-service
                port:
                  name: api-port

---
